export './cities_by_postalcode.dart';

final List<Map<String, String>> postalCodesList = <Map<String, String>>[
  {'postalCode': '9183', 'city': 'EL ABBADETT', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9180', 'city': 'OULED HAFFOUZ', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9174', 'city': 'ERRADHA', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9173', 'city': 'EL KHECHEM', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9172', 'city': 'GOUBRAR', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9171', 'city': 'LESSOUDA', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9170', 'city': 'REGUEB', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9169', 'city': 'OULED MNASSER', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9159', 'city': 'ESSALAMA', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9158', 'city': 'EL MECHE', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9154', 'city': 'EL BOUAA', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9151', 'city': 'EL FOUNI', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9150', 'city': 'MEZZOUNA', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9149', 'city': 'ENNASR', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9144', 'city': 'MABROUKA', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9143', 'city': 'BORJ EL KARMA', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9142', 'city': 'REMILA', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9141', 'city': 'EL MAKAREM', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9140', 'city': 'MAKNASSY', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9139', 'city': 'EL GUELLEL', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9133', 'city': 'EL HAOUAMED', 'governorate': 'SIDI BOUZID'},
  {
    'postalCode': '9132',
    'city': 'CITE EL KAOUAFEL',
    'governorate': 'SIDI BOUZID'
  },
  {'postalCode': '9131', 'city': 'EL HICHRIA', 'governorate': 'SIDI BOUZID'},
  {
    'postalCode': '9127',
    'city': 'MERFEG EL FRAOU',
    'governorate': 'SIDI BOUZID'
  },
  {'postalCode': '9126', 'city': 'ENNOUAIEL', 'governorate': 'SIDI BOUZID'},
  {
    'postalCode': '9125',
    'city': 'CITE OULED BEL HEDI',
    'governorate': 'SIDI BOUZID'
  },
  {'postalCode': '9124', 'city': 'KHORCHEF', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9123', 'city': 'KSAR EL MZARA', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9122', 'city': 'CEBALA', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9121', 'city': 'SOUK JEDID', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9120', 'city': 'BEN AOUN', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9117', 'city': 'ELWOUROUD', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9116', 'city': 'DHOUIBET', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9115', 'city': 'SAIDA', 'governorate': 'SIDI BOUZID'},
  {
    'postalCode': '9114',
    'city': 'MZEL BOUZAIENE',
    'governorate': 'SIDI BOUZID'
  },
  {'postalCode': '9113', 'city': 'BIR EL HAFEY', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9112', 'city': 'EL FAIEDH', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9111', 'city': 'OUM EL ADHAM', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9110', 'city': 'JELMA', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9100', 'city': 'SIDI BOUZID', 'governorate': 'SIDI BOUZID'},
  {'postalCode': '9084', 'city': 'EL AYAYDA', 'governorate': 'BEJA'},
  {'postalCode': '9083', 'city': 'GRAME', 'governorate': 'BEJA'},
  {'postalCode': '9080', 'city': 'GOUBELLAT', 'governorate': 'BEJA'},
  {'postalCode': '9075', 'city': 'EL HERI', 'governorate': 'BEJA'},
  {'postalCode': '9071', 'city': 'GRIAAT', 'governorate': 'BEJA'},
  {'postalCode': '9070', 'city': 'MEJEZEL BAB', 'governorate': 'BEJA'},
  {'postalCode': '9062', 'city': 'AINTOUNGA', 'governorate': 'BEJA'},
  {'postalCode': '9061', 'city': 'ESSKHIRA', 'governorate': 'BEJA'},
  {'postalCode': '9060', 'city': 'TESTOUR', 'governorate': 'BEJA'},
  {'postalCode': '9052', 'city': 'HAMMAM SAYALA', 'governorate': 'BEJA'},
  {'postalCode': '9046', 'city': 'FADDEN ESSOUK', 'governorate': 'BEJA'},
  {'postalCode': '9044', 'city': 'SIDI NSAR', 'governorate': 'BEJA'},
  {'postalCode': '9042', 'city': 'DJEBBA', 'governorate': 'BEJA'},
  {'postalCode': '9040', 'city': 'TEBOURSOUK', 'governorate': 'BEJA'},
  {'postalCode': '9034', 'city': 'SIDI MEDIENE', 'governorate': 'BEJA'},
  {'postalCode': '9032', 'city': 'DOUGGA', 'governorate': 'BEJA'},
  {'postalCode': '9031', 'city': 'EL MZARA', 'governorate': 'BEJA'},
  {'postalCode': '9030', 'city': 'ZAHRET MEDIENE', 'governorate': 'BEJA'},
  {'postalCode': '9029', 'city': 'SIDI FREJ', 'governorate': 'BEJA'},
  {'postalCode': '9023', 'city': 'EL MAAGOULA', 'governorate': 'BEJA'},
  {'postalCode': '9022', 'city': 'THIBAR', 'governorate': 'BEJA'},
  {'postalCode': '9021', 'city': 'SIDI SMAIL', 'governorate': 'BEJA'},
  {'postalCode': '9015', 'city': 'EL KSAR', 'governorate': 'BEJA'},
  {'postalCode': '9014', 'city': 'ESSLOUGUIA', 'governorate': 'BEJA'},
  {'postalCode': '9013', 'city': 'OUED ZARGA', 'governorate': 'BEJA'},
  {'postalCode': '9012', 'city': 'OUECHTATA', 'governorate': 'BEJA'},
  {'postalCode': '9011', 'city': 'TABABA', 'governorate': 'BEJA'},
  {'postalCode': '9010', 'city': 'NEFZA', 'governorate': 'BEJA'},
  {'postalCode': '9000', 'city': 'BEJA', 'governorate': 'BEJA'},
  {'postalCode': '8196', 'city': 'CITE ETTATAOUER', 'governorate': 'JENDOUBA'},
  {'postalCode': '8195', 'city': 'ESSAADA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8194', 'city': 'HAKIM', 'governorate': 'JENDOUBA'},
  {'postalCode': '8193', 'city': 'SIDI MESKINE', 'governorate': 'JENDOUBA'},
  {'postalCode': '8192', 'city': 'EL HAMDIA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8189', 'city': 'JENDOUBA NORD', 'governorate': 'JENDOUBA'},
  {'postalCode': '8185', 'city': 'EDKHAIELIA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8173', 'city': 'SOUIVIRANE', 'governorate': 'JENDOUBA'},
  {'postalCode': '8170', 'city': 'BOU SALEM', 'governorate': 'JENDOUBA'},
  {'postalCode': '8162', 'city': 'OUED EL MAADEN', 'governorate': 'JENDOUBA'},
  {'postalCode': '8161', 'city': 'OUERGUECH', 'governorate': 'JENDOUBA'},
  {'postalCode': '8160', 'city': 'GHARDIMAOU', 'governorate': 'JENDOUBA'},
  {'postalCode': '8153', 'city': 'EL MELGA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8145', 'city': 'HEDHIL', 'governorate': 'JENDOUBA'},
  {'postalCode': '8143', 'city': 'BADROUNA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8142', 'city': 'AIN EL BEYA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8141', 'city': 'JANIOURA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8140', 'city': 'FERNANA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8136', 'city': 'HAMMAM BOURGUIBA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8135', 'city': 'OUED HILEL', 'governorate': 'JENDOUBA'},
  {'postalCode': '8134', 'city': 'TEBAINIA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8133', 'city': 'AIN KRIMA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8132', 'city': 'SOUK JEMAA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8131', 'city': 'SOUK ESSEBI', 'governorate': 'JENDOUBA'},
  {'postalCode': '8130', 'city': 'AIN DRAHAM', 'governorate': 'JENDOUBA'},
  {'postalCode': '8128', 'city': 'JABALLAH', 'governorate': 'JENDOUBA'},
  {'postalCode': '8127', 'city': 'BRIREM', 'governorate': 'JENDOUBA'},
  {'postalCode': '8126', 'city': 'BALIA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8124', 'city': 'EL MARJA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8122', 'city': 'ESSANABEL', 'governorate': 'JENDOUBA'},
  {'postalCode': '8121', 'city': 'BABOUCH', 'governorate': 'JENDOUBA'},
  {'postalCode': '8116', 'city': 'BOU AOUENE', 'governorate': 'JENDOUBA'},
  {'postalCode': '8115', 'city': 'OUED MELIZ', 'governorate': 'JENDOUBA'},
  {'postalCode': '8114', 'city': 'BENI MTIR', 'governorate': 'JENDOUBA'},
  {'postalCode': '8112', 'city': 'AIN ESSOBOH', 'governorate': 'JENDOUBA'},
  {'postalCode': '8111', 'city': 'BEN BECHIR', 'governorate': 'JENDOUBA'},
  {'postalCode': '8110', 'city': 'TABARKA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8100', 'city': 'JENDOUBA', 'governorate': 'JENDOUBA'},
  {'postalCode': '8099', 'city': 'ZAOUIET JEDIDI', 'governorate': 'NABEUL'},
  {'postalCode': '8096', 'city': 'HAMMAM JEBLI', 'governorate': 'NABEUL'},
  {'postalCode': '8094', 'city': 'MELLOUL', 'governorate': 'NABEUL'},
  {'postalCode': '8093', 'city': 'AIN TEBOURNOK', 'governorate': 'NABEUL'},
  {
    'postalCode': '8092',
    'city': 'GROMBALIA EZZOUHOUR',
    'governorate': 'NABEUL'
  },
  {'postalCode': '8091', 'city': 'ERRAHMA', 'governorate': 'NABEUL'},
  {'postalCode': '8090', 'city': 'KELIBIA', 'governorate': 'NABEUL'},
  {'postalCode': '8089', 'city': 'FARTOUNA', 'governorate': 'NABEUL'},
  {'postalCode': '8085', 'city': 'SELTENE', 'governorate': 'NABEUL'},
  {'postalCode': '8084', 'city': 'TURKI', 'governorate': 'NABEUL'},
  {'postalCode': '8083', 'city': 'RAININE', 'governorate': 'NABEUL'},
  {'postalCode': '8082', 'city': 'KHANGUET HOJJAJ', 'governorate': 'NABEUL'},
  {'postalCode': '8076', 'city': 'KORBA HACHED', 'governorate': 'NABEUL'},
  {'postalCode': '8075', 'city': 'DAR CHAABANE PLAGE', 'governorate': 'NABEUL'},
  {'postalCode': '8074', 'city': 'TAZOUGRANE', 'governorate': 'NABEUL'},
  {'postalCode': '8073', 'city': "M'RAISSA", 'governorate': 'NABEUL'},
  {'postalCode': '8071', 'city': 'TEFELOUN', 'governorate': 'NABEUL'},
  {'postalCode': '8070', 'city': 'KORBA', 'governorate': 'NABEUL'},
  {'postalCode': '8069', 'city': 'KELIBIA CHARGUIA', 'governorate': 'NABEUL'},
  {'postalCode': '8068', 'city': 'OUED SOUIHIL', 'governorate': 'NABEUL'},
  {'postalCode': '8065', 'city': 'OUED EL KHATEF', 'governorate': 'NABEUL'},
  {'postalCode': '8064', 'city': 'SKALBA', 'governorate': 'NABEUL'},
  {'postalCode': '8063', 'city': 'BOUCHARRAY', 'governorate': 'NABEUL'},
  {'postalCode': '8062', 'city': 'NABEUL THAMEUR', 'governorate': 'NABEUL'},
  {'postalCode': '8061', 'city': 'SIDI DHAHER', 'governorate': 'NABEUL'},
  {'postalCode': '8060', 'city': 'BENI KHIAR', 'governorate': 'NABEUL'},
  {'postalCode': '8057', 'city': 'BOUFICHA', 'governorate': 'NABEUL'},
  {'postalCode': '8056', 'city': 'BARRAKET ESSAHEL', 'governorate': 'NABEUL'},
  {'postalCode': '8055', 'city': 'DAR ELLOUCHE', 'governorate': 'NABEUL'},
  {'postalCode': '8054', 'city': 'EL OUERDIANE', 'governorate': 'NABEUL'},
  {'postalCode': '8053', 'city': 'GARAAT SASSI', 'governorate': 'NABEUL'},
  {'postalCode': '8052', 'city': 'NIANOU', 'governorate': 'NABEUL'},
  {'postalCode': '8051', 'city': 'CHERIFATE', 'governorate': 'NABEUL'},
  {'postalCode': '8050', 'city': 'HAMMAMET', 'governorate': 'NABEUL'},
  {'postalCode': '8046', 'city': 'ZAOUIET EL MAGAIES', 'governorate': 'NABEUL'},
  {'postalCode': '8045', 'city': 'EL HAOUARIA', 'governorate': 'NABEUL'},
  {'postalCode': '8044', 'city': 'EL MIDA', 'governorate': 'NABEUL'},
  {'postalCode': '8043', 'city': 'BOU JERIDA', 'governorate': 'NABEUL'},
  {'postalCode': '8042', 'city': 'BIR BOUREGBA', 'governorate': 'NABEUL'},
  {'postalCode': '8041', 'city': 'KORBOUS', 'governorate': 'NABEUL'},
  {'postalCode': '8040', 'city': 'BOUARGOUB', 'governorate': 'NABEUL'},
  {'postalCode': '8036', 'city': 'BOU KRIM', 'governorate': 'NABEUL'},
  {'postalCode': '8035', 'city': 'AZMOUR', 'governorate': 'NABEUL'},
  {'postalCode': '8034', 'city': 'LEBNA', 'governorate': 'NABEUL'},
  {'postalCode': '8033', 'city': 'DIAR EL HOJJEJ', 'governorate': 'NABEUL'},
  {'postalCode': '8032', 'city': 'SIDI JEDIDI', 'governorate': 'NABEUL'},
  {'postalCode': '8031', 'city': 'BIR MROUA', 'governorate': 'NABEUL'},
  {'postalCode': '8030', 'city': 'GROMBALIA', 'governorate': 'NABEUL'},
  {'postalCode': '8026', 'city': 'SAHEB JEBEL', 'governorate': 'NABEUL'},
  {'postalCode': '8025', 'city': 'HAMMAM EL GHEZAZ', 'governorate': 'NABEUL'},
  {'postalCode': '8024', 'city': 'TAZARKA', 'governorate': 'NABEUL'},
  {'postalCode': '8023', 'city': 'ESSOMAA', 'governorate': 'NABEUL'},
  {'postalCode': '8022', 'city': 'BELLI', 'governorate': 'NABEUL'},
  {'postalCode': '8021', 'city': 'BENI KHALLED', 'governorate': 'NABEUL'},
  {'postalCode': '8020', 'city': 'SOLIMAN', 'governorate': 'NABEUL'},
  {'postalCode': '8015', 'city': 'MZEL HORR', 'governorate': 'NABEUL'},
  {'postalCode': '8014', 'city': 'BIR DRASSEN', 'governorate': 'NABEUL'},
  {'postalCode': '8013', 'city': 'MAAMOURA', 'governorate': 'NABEUL'},
  {'postalCode': '8012', 'city': 'FONDOUK EL JEDID', 'governorate': 'NABEUL'},
  {
    'postalCode': '8011',
    'city': 'DAR CHAABANE EL FEHRI',
    'governorate': 'NABEUL'
  },
  {'postalCode': '8010', 'city': 'MENZEL BOUZELFA', 'governorate': 'NABEUL'},
  {'postalCode': '8000', 'city': 'NABEUL', 'governorate': 'NABEUL'},
  {'postalCode': '7195', 'city': 'EL MAHASSEN NORD', 'governorate': 'LE KEF'},
  {'postalCode': '7194', 'city': 'OUED SOUANI', 'governorate': 'LE KEF'},
  {'postalCode': '7182', 'city': 'ELLES', 'governorate': 'LE KEF'},
  {'postalCode': '7180', 'city': 'LE SERS', 'governorate': 'LE KEF'},
  {'postalCode': '7170', 'city': 'DAHMANI', 'governorate': 'LE KEF'},
  {'postalCode': '7160', 'city': 'EL KSOUR', 'governorate': 'LE KEF'},
  {'postalCode': '7153', 'city': 'JAZZA', 'governorate': 'LE KEF'},
  {'postalCode': '7151', 'city': 'MENZEL SALEM', 'governorate': 'LE KEF'},
  {'postalCode': '7150', 'city': 'TAJEROUINE', 'governorate': 'LE KEF'},
  {'postalCode': '7141', 'city': 'TELL GHOUZLANE', 'governorate': 'LE KEF'},
  {'postalCode': '7136', 'city': 'BOU JABEUR', 'governorate': 'LE KEF'},
  {'postalCode': '7135', 'city': 'AIN SINANE', 'governorate': 'LE KEF'},
  {'postalCode': '7134', 'city': 'ZAAFRANE', 'governorate': 'LE KEF'},
  {'postalCode': '7133', 'city': 'SIDI MTIR', 'governorate': 'LE KEF'},
  {'postalCode': '7132', 'city': 'MAHJOUBA', 'governorate': 'LE KEF'},
  {'postalCode': '7131', 'city': 'SIDI KHIAR', 'governorate': 'LE KEF'},
  {'postalCode': '7130', 'city': 'KALAA SENAN', 'governorate': 'LE KEF'},
  {'postalCode': '7125', 'city': 'AIN EL KARMA', 'governorate': 'LE KEF'},
  {'postalCode': '7123', 'city': 'SIDI AHMED SALAH', 'governorate': 'LE KEF'},
  {'postalCode': '7121', 'city': 'BARNOUSSA', 'governorate': 'LE KEF'},
  {'postalCode': '7120', 'city': 'ESSAKIA', 'governorate': 'LE KEF'},
  {'postalCode': '7116', 'city': 'BAHRA', 'governorate': 'LE KEF'},
  {'postalCode': '7115', 'city': 'ZITOUNA', 'governorate': 'LE KEF'},
  {'postalCode': '7114', 'city': 'JERISSA', 'governorate': 'LE KEF'},
  {'postalCode': '7113', 'city': 'KALAA EL KHASBA', 'governorate': 'LE KEF'},
  {'postalCode': '7112', 'city': 'TOUIREF', 'governorate': 'LE KEF'},
  {'postalCode': '7111', 'city': 'OUED MELLEGUE', 'governorate': 'LE KEF'},
  {'postalCode': '7110', 'city': 'NEBEUR', 'governorate': 'LE KEF'},
  {'postalCode': '7100', 'city': 'KEF', 'governorate': 'LE KEF'},
  {
    'postalCode': '7098',
    'city': 'EL GARIA RAS JEBEL',
    'governorate': 'BIZERTE'
  },
  {'postalCode': '7097', 'city': 'EL GUETMA', 'governorate': 'BIZERTE'},
  {'postalCode': '7094', 'city': 'BORJ CHALLOUF', 'governorate': 'BIZERTE'},
  {'postalCode': '7093', 'city': 'SIDI ALI CHEBAB', 'governorate': 'BIZERTE'},
  {'postalCode': '7081', 'city': 'KHETMINE', 'governorate': 'BIZERTE'},
  {'postalCode': '7080', 'city': 'MZEL JEMIL', 'governorate': 'BIZERTE'},
  {'postalCode': '7075', 'city': 'BENI ATTA', 'governorate': 'BIZERTE'},
  {
    'postalCode': '7072',
    'city': 'MZEL BOURGUIBA ENNAJAH',
    'governorate': 'BIZERTE'
  },
  {'postalCode': '7071', 'city': 'BIZERTE HACHED', 'governorate': 'BIZERTE'},
  {'postalCode': '7070', 'city': 'RAS JEBEL', 'governorate': 'BIZERTE'},
  {'postalCode': '7064', 'city': 'BOU ZARRIA', 'governorate': 'BIZERTE'},
  {'postalCode': '7063', 'city': 'UTIQUE NOUVELLE', 'governorate': 'BIZERTE'},
  {
    'postalCode': '7061',
    'city': 'BIZERTE BAB MATEUR',
    'governorate': 'BIZERTE'
  },
  {'postalCode': '7060', 'city': 'UTIQUE', 'governorate': 'BIZERTE'},
  {'postalCode': '7053', 'city': 'BIZERTE BOUGAFTA', 'governorate': 'BIZERTE'},
  {'postalCode': '7050', 'city': 'MZEL BOURGUIBA', 'governorate': 'BIZERTE'},
  {'postalCode': '7045', 'city': 'RAF RAF  PLAGE', 'governorate': 'BIZERTE'},
  {'postalCode': '7043', 'city': 'BACH HAMBA', 'governorate': 'BIZERTE'},
  {'postalCode': '7041', 'city': 'LOUATA', 'governorate': 'BIZERTE'},
  {'postalCode': '7040', 'city': 'GHEZALA', 'governorate': 'BIZERTE'},
  {'postalCode': '7036', 'city': 'TESKRAYA', 'governorate': 'BIZERTE'},
  {'postalCode': '7035', 'city': 'MZEL ABDERRAHMAN', 'governorate': 'BIZERTE'},
  {'postalCode': '7034', 'city': 'METLINE', 'governorate': 'BIZERTE'},
  {'postalCode': '7033', 'city': 'GHAR EL MELH', 'governorate': 'BIZERTE'},
  {'postalCode': '7032', 'city': 'TINJA', 'governorate': 'BIZERTE'},
  {'postalCode': '7031', 'city': 'TAMRA', 'governorate': 'BIZERTE'},
  {'postalCode': '7030', 'city': 'MATEUR', 'governorate': 'BIZERTE'},
  {'postalCode': '7027', 'city': 'METHLINE', 'governorate': 'BIZERTE'},
  {'postalCode': '7026', 'city': 'EL AZIB', 'governorate': 'BIZERTE'},
  {'postalCode': '7025', 'city': 'SOUNINE', 'governorate': 'BIZERTE'},
  {'postalCode': '7024', 'city': 'ZOUAOUINE', 'governorate': 'BIZERTE'},
  {'postalCode': '7023', 'city': 'SIDI OTHMAN', 'governorate': 'BIZERTE'},
  {'postalCode': '7022', 'city': 'MATEUR HACHED', 'governorate': 'BIZERTE'},
  {'postalCode': '7021', 'city': 'JARZOUNA', 'governorate': 'BIZERTE'},
  {'postalCode': '7020', 'city': 'JOUMINE', 'governorate': 'BIZERTE'},
  {'postalCode': '7016', 'city': 'EL ALIA', 'governorate': 'BIZERTE'},
  {'postalCode': '7015', 'city': 'RAF RAF', 'governorate': 'BIZERTE'},
  {'postalCode': '7014', 'city': 'EL AOUSJA', 'governorate': 'BIZERTE'},
  {'postalCode': '7013', 'city': 'AIN GHELAL', 'governorate': 'BIZERTE'},
  {'postalCode': '7012', 'city': 'BAZINA', 'governorate': 'BIZERTE'},
  {'postalCode': '7011', 'city': 'PECHERIE', 'governorate': 'BIZERTE'},
  {'postalCode': '7010', 'city': 'SEJNANE', 'governorate': 'BIZERTE'},
  {'postalCode': '7000', 'city': 'BIZERTE', 'governorate': 'BIZERTE'},
  {'postalCode': '6196', 'city': 'RAS EL MA', 'governorate': 'SILIANA'},
  {'postalCode': '6183', 'city': 'MEDIOUNA', 'governorate': 'SILIANA'},
  {'postalCode': '6180', 'city': 'BOUARADA', 'governorate': 'SILIANA'},
  {'postalCode': '6174', 'city': 'SIDI SAID', 'governorate': 'SILIANA'},
  {'postalCode': '6173', 'city': 'SODGA', 'governorate': 'SILIANA'},
  {'postalCode': '6172', 'city': 'AIN ZRIG', 'governorate': 'SILIANA'},
  {'postalCode': '6170', 'city': 'BARGOU', 'governorate': 'SILIANA'},
  {'postalCode': '6152', 'city': 'HABEBSA SUD', 'governorate': 'SILIANA'},
  {'postalCode': '6151', 'city': 'EL KHALSA', 'governorate': 'SILIANA'},
  {'postalCode': '6150', 'city': 'ROHIA', 'governorate': 'SILIANA'},
  {'postalCode': '6143', 'city': 'ESSAFINA', 'governorate': 'SILIANA'},
  {'postalCode': '6142', 'city': 'SNED HADDAD', 'governorate': 'SILIANA'},
  {'postalCode': '6141', 'city': 'KESRA SUPERIEURE', 'governorate': 'SILIANA'},
  {'postalCode': '6140', 'city': 'MAKTHAR', 'governorate': 'SILIANA'},
  {'postalCode': '6136', 'city': 'HAMMAM BIADHA', 'governorate': 'SILIANA'},
  {'postalCode': '6135', 'city': 'BOUJLIDA', 'governorate': 'SILIANA'},
  {'postalCode': '6134', 'city': 'BOU ROUIS FILAHI', 'governorate': 'SILIANA'},
  {'postalCode': '6133', 'city': 'EL GARIA', 'governorate': 'SILIANA'},
  {'postalCode': '6131', 'city': 'ELMANSOURA', 'governorate': 'SILIANA'},
  {'postalCode': '6126', 'city': 'SIDI AYED', 'governorate': 'SILIANA'},
  {'postalCode': '6125', 'city': 'BORJ MESSAOUDI', 'governorate': 'SILIANA'},
  {'postalCode': '6124', 'city': 'SIDI HAMADA', 'governorate': 'SILIANA'},
  {'postalCode': '6123', 'city': 'EL KANTRA', 'governorate': 'SILIANA'},
  {'postalCode': '6122', 'city': 'DOUKHANIA', 'governorate': 'SILIANA'},
  {'postalCode': '6121', 'city': 'EL AKSAB', 'governorate': 'SILIANA'},
  {'postalCode': '6120', 'city': 'KRIB', 'governorate': 'SILIANA'},
  {'postalCode': '6116', 'city': 'EL AROUSSA', 'governorate': 'SILIANA'},
  {'postalCode': '6115', 'city': 'BOU SADIA', 'governorate': 'SILIANA'},
  {'postalCode': '6114', 'city': 'KESRA', 'governorate': 'SILIANA'},
  {'postalCode': '6113', 'city': 'BOUROUIS', 'governorate': 'SILIANA'},
  {'postalCode': '6112', 'city': 'KRIB GARE', 'governorate': 'SILIANA'},
  {'postalCode': '6111', 'city': 'EL ALKHOUAT', 'governorate': 'SILIANA'},
  {'postalCode': '6110', 'city': 'GAAFOUR', 'governorate': 'SILIANA'},
  {'postalCode': '6100', 'city': 'SILIANA', 'governorate': 'SILIANA'},
  {'postalCode': '6099', 'city': 'GABES EL HIDAYA', 'governorate': 'GABES'},
  {'postalCode': '6095', 'city': 'CHENCHOU', 'governorate': 'GABES'},
  {'postalCode': '6092', 'city': 'BECHIMA', 'governorate': 'GABES'},
  {'postalCode': '6089', 'city': 'METOUIA EL MAYA', 'governorate': 'GABES'},
  {'postalCode': '6081', 'city': 'BETAHRA', 'governorate': 'GABES'},
  {'postalCode': '6080', 'city': 'MARETH', 'governorate': 'GABES'},
  {'postalCode': '6072', 'city': 'ZRIG', 'governorate': 'GABES'},
  {'postalCode': '6071', 'city': 'GABES PORT', 'governorate': 'GABES'},
  {'postalCode': '6070', 'city': 'MATMATA', 'governorate': 'GABES'},
  {'postalCode': '6062', 'city': 'BENI GHILOUF', 'governorate': 'GABES'},
  {'postalCode': '6061', 'city': 'CHATT ESSALEM', 'governorate': 'GABES'},
  {'postalCode': '6060', 'city': 'EL HAMMA SUD', 'governorate': 'GABES'},
  {'postalCode': '6056', 'city': 'EZZERKINE', 'governorate': 'GABES'},
  {'postalCode': '6055', 'city': 'DKHLILET TOUJANE', 'governorate': 'GABES'},
  {'postalCode': '6054', 'city': 'TAMEZRAT', 'governorate': 'GABES'},
  {'postalCode': '6052', 'city': 'OUEDHREF', 'governorate': 'GABES'},
  {'postalCode': '6051', 'city': 'NAHAL', 'governorate': 'GABES'},
  {'postalCode': '6046', 'city': 'SIDI TOUATI', 'governorate': 'GABES'},
  {'postalCode': '6045', 'city': 'TOUJENE', 'governorate': 'GABES'},
  {'postalCode': '6044', 'city': 'NLLE MATMATA', 'governorate': 'GABES'},
  {'postalCode': '6043', 'city': 'LAFFAM', 'governorate': 'GABES'},
  {'postalCode': '6042', 'city': 'EL AKARIT', 'governorate': 'GABES'},
  {'postalCode': '6041', 'city': 'CHENINI DE GABES', 'governorate': 'GABES'},
  {'postalCode': '6040', 'city': 'GABES REPUBLIQUE', 'governorate': 'GABES'},
  {'postalCode': '6036', 'city': 'KETTANA', 'governorate': 'GABES'},
  {'postalCode': '6035', 'city': 'AIN TOUNINE', 'governorate': 'GABES'},
  {'postalCode': '6034', 'city': 'TECHNINE', 'governorate': 'GABES'},
  {'postalCode': '6033', 'city': 'CITE EL AMEL', 'governorate': 'GABES'},
  {'postalCode': '6032', 'city': 'TEBOULBOU', 'governorate': 'GABES'},
  {'postalCode': '6031', 'city': 'BOU CHEMA', 'governorate': 'GABES'},
  {'postalCode': '6030', 'city': 'MZEL EL HABIB', 'governorate': 'GABES'},
  {'postalCode': '6027', 'city': 'BOUATTOUCHE', 'governorate': 'GABES'},
  {'postalCode': '6026', 'city': 'ZARATH', 'governorate': 'GABES'},
  {'postalCode': '6025', 'city': 'BENI ZELTEN', 'governorate': 'GABES'},
  {'postalCode': '6024', 'city': 'NLLE ZRAOUA', 'governorate': 'GABES'},
  {'postalCode': '6023', 'city': 'EL ALAYA', 'governorate': 'GABES'},
  {'postalCode': '6022', 'city': 'EL MDOU', 'governorate': 'GABES'},
  {'postalCode': '6021', 'city': 'GHANNOUCH', 'governorate': 'GABES'},
  {'postalCode': '6020', 'city': 'EL HAMMA', 'governorate': 'GABES'},
  {'postalCode': '6016', 'city': 'ARRAM', 'governorate': 'GABES'},
  {'postalCode': '6015', 'city': 'OUYOUN EZZARKINE', 'governorate': 'GABES'},
  {'postalCode': '6014', 'city': "M'TOURECH", 'governorate': 'GABES'},
  {'postalCode': '6013', 'city': 'SOMBAT', 'governorate': 'GABES'},
  {'postalCode': '6012', 'city': 'SIDI BOULBABA', 'governorate': 'GABES'},
  {'postalCode': '6011', 'city': 'GAB�S EL MANARA', 'governorate': 'GABES'},
  {'postalCode': '6010', 'city': 'EL METOUIA', 'governorate': 'GABES'},
  {'postalCode': '6001', 'city': 'GABES HACHED', 'governorate': 'GABES'},
  {'postalCode': '6000', 'city': 'GABES', 'governorate': 'GABES'},
  {'postalCode': '5199', 'city': 'MAHDIA EZZAHRA', 'governorate': 'MAHDIA'},
  {'postalCode': '5193', 'city': 'OUED BEJA', 'governorate': 'MAHDIA'},
  {'postalCode': '5192', 'city': 'ZELBA', 'governorate': 'MAHDIA'},
  {'postalCode': '5190', 'city': 'SIDI ALOUANE', 'governorate': 'MAHDIA'},
  {'postalCode': '5189', 'city': 'KSOUR ESSAF HACHED', 'governorate': 'MAHDIA'},
  {'postalCode': '5180', 'city': 'KSOUR ESSAF', 'governorate': 'MAHDIA'},
  {'postalCode': '5170', 'city': 'CHEBBA', 'governorate': 'MAHDIA'},
  {'postalCode': '5160', 'city': 'EL JEM', 'governorate': 'MAHDIA'},
  {'postalCode': '5154', 'city': 'MEHARZA', 'governorate': 'MAHDIA'},
  {'postalCode': '5153', 'city': 'RIADH BOUHLEL', 'governorate': 'MAHDIA'},
  {'postalCode': '5150', 'city': 'MAHDIA REPUBLIQUE', 'governorate': 'MAHDIA'},
  {'postalCode': '5145', 'city': 'MANSOURA SOUASSI', 'governorate': 'MAHDIA'},
  {'postalCode': '5144', 'city': 'JEMAMLA', 'governorate': 'MAHDIA'},
  {'postalCode': '5143', 'city': 'CHEHIMET EL KEBLIA', 'governorate': 'MAHDIA'},
  {'postalCode': '5141', 'city': 'CHIBA', 'governorate': 'MAHDIA'},
  {'postalCode': '5140', 'city': 'SOUASSI', 'governorate': 'MAHDIA'},
  {'postalCode': '5136', 'city': 'EL GHEDHABNA', 'governorate': 'MAHDIA'},
  {'postalCode': '5135', 'city': 'NAFFATIA', 'governorate': 'MAHDIA'},
  {'postalCode': '5134', 'city': 'SIDI ZID', 'governorate': 'MAHDIA'},
  {'postalCode': '5133', 'city': 'CHAHDA', 'governorate': 'MAHDIA'},
  {'postalCode': '5132', 'city': 'SAKIET EL KHADEM', 'governorate': 'MAHDIA'},
  {'postalCode': '5131', 'city': 'EL HKAMIA', 'governorate': 'MAHDIA'},
  {'postalCode': '5130', 'city': 'CHORBANE', 'governorate': 'MAHDIA'},
  {'postalCode': '5126', 'city': 'SALAKTA', 'governorate': 'MAHDIA'},
  {'postalCode': '5125', 'city': 'BOU HELLAL SUD', 'governorate': 'MAHDIA'},
  {'postalCode': '5124', 'city': 'TLELSA', 'governorate': 'MAHDIA'},
  {'postalCode': '5123', 'city': 'CHEHIMET', 'governorate': 'MAHDIA'},
  {'postalCode': '5122', 'city': 'MZEL HACHED', 'governorate': 'MAHDIA'},
  {'postalCode': '5121', 'city': 'REJICHE', 'governorate': 'MAHDIA'},
  {'postalCode': '5120', 'city': 'OULED CHAMAKH', 'governorate': 'MAHDIA'},
  {'postalCode': '5117', 'city': 'ESSAAD', 'governorate': 'MAHDIA'},
  {'postalCode': '5116', 'city': 'SIDI ASSAKER', 'governorate': 'MAHDIA'},
  {'postalCode': '5115', 'city': 'EL BRADAA', 'governorate': 'MAHDIA'},
  {'postalCode': '5114', 'city': 'MELLOULECH', 'governorate': 'MAHDIA'},
  {'postalCode': '5113', 'city': "H'BIRA", 'governorate': 'MAHDIA'},
  {'postalCode': '5112', 'city': 'KERKER', 'governorate': 'MAHDIA'},
  {'postalCode': '5111', 'city': 'MAHDIA HIBOUN', 'governorate': 'MAHDIA'},
  {'postalCode': '5110', 'city': 'BOU MERDES', 'governorate': 'MAHDIA'},
  {'postalCode': '5100', 'city': 'MAHDIA', 'governorate': 'MAHDIA'},
  {'postalCode': '5099', 'city': 'LAMTA', 'governorate': 'MONASTIR'},
  {'postalCode': '5092', 'city': 'BHIRA', 'governorate': 'MONASTIR'},
  {'postalCode': '5091', 'city': 'CHRAF', 'governorate': 'MONASTIR'},
  {'postalCode': '5090', 'city': 'BEKALTA', 'governorate': 'MONASTIR'},
  {
    'postalCode': '5089',
    'city': 'CITE EL BASSATINE',
    'governorate': 'MONASTIR'
  },
  {'postalCode': '5080', 'city': 'TEBOULBA', 'governorate': 'MONASTIR'},
  {'postalCode': '5079', 'city': 'MONASTIR GARE', 'governorate': 'MONASTIR'},
  {'postalCode': '5076', 'city': 'MENARA', 'governorate': 'MONASTIR'},
  {'postalCode': '5071', 'city': 'AMIRAT HAJJEJ', 'governorate': 'MONASTIR'},
  {'postalCode': '5070', 'city': 'KSAR HELLAL', 'governorate': 'MONASTIR'},
  {'postalCode': '5066', 'city': 'SOUKRINE', 'governorate': 'MONASTIR'},
  {
    'postalCode': '5065',
    'city': 'MONASTIR AEROPORT',
    'governorate': 'MONASTIR'
  },
  {'postalCode': '5063', 'city': 'BOU DHER', 'governorate': 'MONASTIR'},
  {'postalCode': '5062', 'city': 'AMIRAT HATEM', 'governorate': 'MONASTIR'},
  {'postalCode': '5061', 'city': 'SIDI AMEUR', 'governorate': 'MONASTIR'},
  {
    'postalCode': '5060',
    'city': 'MONASTIR REPUBLIQUE',
    'governorate': 'MONASTIR'
  },
  {'postalCode': '5054', 'city': 'AMIRAT TOUAZRA', 'governorate': 'MONASTIR'},
  {'postalCode': '5053', 'city': 'AMIRAT FEHOUL', 'governorate': 'MONASTIR'},
  {'postalCode': '5052', 'city': 'BOU OTHMAN', 'governorate': 'MONASTIR'},
  {'postalCode': '5051', 'city': 'MOKNINE JADIDA', 'governorate': 'MONASTIR'},
  {'postalCode': '5050', 'city': 'MOKNINE', 'governorate': 'MONASTIR'},
  {'postalCode': '5046', 'city': 'MLICHETTE', 'governorate': 'MONASTIR'},
  {'postalCode': '5045', 'city': 'MZAOUGHA', 'governorate': 'MONASTIR'},
  {'postalCode': '5044', 'city': 'SIDI BANNOUR', 'governorate': 'MONASTIR'},
  {'postalCode': '5043', 'city': 'BIR TAIEB', 'governorate': 'MONASTIR'},
  {'postalCode': '5042', 'city': 'MESJED AISSA', 'governorate': 'MONASTIR'},
  {'postalCode': '5041', 'city': 'MZEL KHIR', 'governorate': 'MONASTIR'},
  {'postalCode': '5040', 'city': 'ZERAMDINE', 'governorate': 'MONASTIR'},
  {'postalCode': '5036', 'city': 'MZEL HARB', 'governorate': 'MONASTIR'},
  {'postalCode': '5035', 'city': 'SAYADA', 'governorate': 'MONASTIR'},
  {'postalCode': '5034', 'city': 'CHERAHIL', 'governorate': 'MONASTIR'},
  {'postalCode': '5033', 'city': 'MZEL HAYET', 'governorate': 'MONASTIR'},
  {'postalCode': '5032', 'city': 'MAZDOUR', 'governorate': 'MONASTIR'},
  {
    'postalCode': '5031',
    'city': 'KSIBET EL MEDIOUNI',
    'governorate': 'MONASTIR'
  },
  {
    'postalCode': '5030',
    'city': 'JEMMAL KHEIREDDINE',
    'governorate': 'MONASTIR'
  },
  {'postalCode': '5028', 'city': 'ZAOUIET KONTECH', 'governorate': 'MONASTIR'},
  {'postalCode': '5027', 'city': 'ETTIAYRA', 'governorate': 'MONASTIR'},
  {'postalCode': '5026', 'city': 'GHENADA', 'governorate': 'MONASTIR'},
  {'postalCode': '5025', 'city': 'BENNANE', 'governorate': 'MONASTIR'},
  {'postalCode': '5024', 'city': 'MZEL FERSI', 'governorate': 'MONASTIR'},
  {'postalCode': '5023', 'city': 'TOUZA', 'governorate': 'MONASTIR'},
  {'postalCode': '5022', 'city': 'MZEL ENNOUR', 'governorate': 'MONASTIR'},
  {'postalCode': '5021', 'city': 'BEMBLA', 'governorate': 'MONASTIR'},
  {'postalCode': '5020', 'city': 'JEMMAL', 'governorate': 'MONASTIR'},
  {'postalCode': '5017', 'city': 'EL HEDADRA', 'governorate': 'MONASTIR'},
  {
    'postalCode': '5016',
    'city': 'KSAR HELLAL RIADH',
    'governorate': 'MONASTIR'
  },
  {'postalCode': '5015', 'city': 'BOU HAJAR', 'governorate': 'MONASTIR'},
  {'postalCode': '5014', 'city': 'BENI HASSEN', 'governorate': 'MONASTIR'},
  {'postalCode': '5013', 'city': 'MZEL KAMEL', 'governorate': 'MONASTIR'},
  {'postalCode': '5012', 'city': 'SAHLINE', 'governorate': 'MONASTIR'},
  {'postalCode': '5011', 'city': 'KHENIS', 'governorate': 'MONASTIR'},
  {'postalCode': '5010', 'city': 'OUERDANINE', 'governorate': 'MONASTIR'},
  {'postalCode': '5000', 'city': 'MONASTIR', 'governorate': 'MONASTIR'},
  {'postalCode': '4294', 'city': 'SAIDANE', 'governorate': 'KEBILI'},
  {'postalCode': '4293', 'city': 'MANSOURA', 'governorate': 'KEBILI'},
  {'postalCode': '4283', 'city': 'NEGGA', 'governorate': 'KEBILI'},
  {'postalCode': '4280', 'city': 'KEBILI BEYEZ', 'governorate': 'KEBILI'},
  {'postalCode': '4274', 'city': 'LIMAGUEZ', 'governorate': 'KEBILI'},
  {'postalCode': '4273', 'city': 'STAFTIMIA', 'governorate': 'KEBILI'},
  {'postalCode': '4264', 'city': 'EL FAOUAR', 'governorate': 'KEBILI'},
  {'postalCode': '4263', 'city': 'JERSINE', 'governorate': 'KEBILI'},
  {'postalCode': '4261', 'city': 'ZAAFRANE DOUZ', 'governorate': 'KEBILI'},
  {'postalCode': '4260', 'city': 'DOUZ', 'governorate': 'KEBILI'},
  {'postalCode': '4253', 'city': 'BECHELLI', 'governorate': 'KEBILI'},
  {'postalCode': '4243', 'city': 'BLIDETTE', 'governorate': 'KEBILI'},
  {'postalCode': '4242', 'city': 'JANOURA', 'governorate': 'KEBILI'},
  {'postalCode': '4237', 'city': 'TELMINE', 'governorate': 'KEBILI'},
  {'postalCode': '4236', 'city': 'BOU ABDALLAH', 'governorate': 'KEBILI'},
  {'postalCode': '4234', 'city': 'EL GOLAA', 'governorate': 'KEBILI'},
  {'postalCode': '4233', 'city': 'RABIA', 'governorate': 'KEBILI'},
  {'postalCode': '4232', 'city': 'TENBIB', 'governorate': 'KEBILI'},
  {'postalCode': '4231', 'city': 'BECHRI', 'governorate': 'KEBILI'},
  {'postalCode': '4230', 'city': 'SOUK EL AHAD', 'governorate': 'KEBILI'},
  {'postalCode': '4224', 'city': 'BAZMA', 'governorate': 'KEBILI'},
  {'postalCode': '4223', 'city': 'FAINASSA', 'governorate': 'KEBILI'},
  {'postalCode': '4222', 'city': 'NOUAFEL', 'governorate': 'KEBILI'},
  {'postalCode': '4215', 'city': 'DOUZ CHARGUI', 'governorate': 'KEBILI'},
  {'postalCode': '4214', 'city': 'JEMNA', 'governorate': 'KEBILI'},
  {'postalCode': '4213', 'city': 'ZAOUIET EL ANAS', 'governorate': 'KEBILI'},
  {'postalCode': '4212', 'city': 'OM SOMAA', 'governorate': 'KEBILI'},
  {'postalCode': '4211', 'city': 'RAHMET', 'governorate': 'KEBILI'},
  {'postalCode': '4210', 'city': 'REGIME MAATOUG', 'governorate': 'KEBILI'},
  {'postalCode': '4200', 'city': 'KEBILI', 'governorate': 'KEBILI'},
  {'postalCode': '4199', 'city': 'DAR DJERBA', 'governorate': 'MEDENINE'},
  {'postalCode': '4195', 'city': 'GACHINE', 'governorate': 'MEDENINE'},
  {'postalCode': '4194', 'city': 'HAMADI EL GHEBLI', 'governorate': 'MEDENINE'},
  {'postalCode': '4193', 'city': "J'MILA", 'governorate': 'MEDENINE'},
  {'postalCode': '4192', 'city': 'JALEL', 'governorate': 'MEDENINE'},
  {'postalCode': '4191', 'city': 'SIDI MAKHLOUF', 'governorate': 'MEDENINE'},
  {'postalCode': '4190', 'city': 'SIDI ZAID', 'governorate': 'MEDENINE'},
  {'postalCode': '4186', 'city': 'MEZRAYA', 'governorate': 'MEDENINE'},
  {'postalCode': '4185', 'city': 'SOUANI', 'governorate': 'MEDENINE'},
  {'postalCode': '4183', 'city': 'OUERSANIA', 'governorate': 'MEDENINE'},
  {'postalCode': '4181', 'city': 'RAGOUBA', 'governorate': 'MEDENINE'},
  {'postalCode': '4180', 'city': 'DJERBA', 'governorate': 'MEDENINE'},
  {'postalCode': '4179', 'city': 'SIDI MEHREZ', 'governorate': 'MEDENINE'},
  {'postalCode': '4176', 'city': 'ARKOU', 'governorate': 'MEDENINE'},
  {'postalCode': '4175', 'city': 'EL MAY', 'governorate': 'MEDENINE'},
  {'postalCode': '4174', 'city': 'HASSI JERBI', 'governorate': 'MEDENINE'},
  {'postalCode': '4173', 'city': 'SOUIHEL', 'governorate': 'MEDENINE'},
  {'postalCode': '4172', 'city': 'JEDARIA', 'governorate': 'MEDENINE'},
  {'postalCode': '4170', 'city': 'ZARZIS', 'governorate': 'MEDENINE'},
  {'postalCode': '4166', 'city': 'OUED ZBIB', 'governorate': 'MEDENINE'},
  {'postalCode': '4165', 'city': 'MAHBOUBINE', 'governorate': 'MEDENINE'},
  {'postalCode': '4164', 'city': 'GRIBIS', 'governorate': 'MEDENINE'},
  {'postalCode': '4163', 'city': 'CHEHBANIA', 'governorate': 'MEDENINE'},
  {'postalCode': '4161', 'city': 'SAYAH', 'governorate': 'MEDENINE'},
  {'postalCode': '4160', 'city': 'BEN GUERDANE', 'governorate': 'MEDENINE'},
  {'postalCode': '4159', 'city': 'CHOUAMAKH', 'governorate': 'MEDENINE'},
  {'postalCode': '4156', 'city': 'GHIZEN', 'governorate': 'MEDENINE'},
  {'postalCode': '4155', 'city': 'GUELLALA', 'governorate': 'MEDENINE'},
  {'postalCode': '4154', 'city': 'EL GRABETE', 'governorate': 'MEDENINE'},
  {'postalCode': '4153', 'city': 'RAS JEDIR', 'governorate': 'MEDENINE'},
  {'postalCode': '4151', 'city': 'KSAR JEDID', 'governorate': 'MEDENINE'},
  {'postalCode': '4150', 'city': 'METHANIA', 'governorate': 'MEDENINE'},
  {'postalCode': '4146', 'city': 'ERRIADH', 'governorate': 'MEDENINE'},
  {'postalCode': '4145', 'city': 'CEDOUIKECHE', 'governorate': 'MEDENINE'},
  {'postalCode': '4144', 'city': 'EL MOUANSA', 'governorate': 'MEDENINE'},
  {'postalCode': '4143', 'city': 'MAGHRAOUI', 'governorate': 'MEDENINE'},
  {'postalCode': '4141', 'city': 'BOU GHRADA', 'governorate': 'MEDENINE'},
  {
    'postalCode': '4137',
    'city': 'ZARZIS ZONE FRANCHE',
    'governorate': 'MEDENINE'
  },
  {'postalCode': '4136', 'city': 'SEDGHANE', 'governorate': 'MEDENINE'},
  {'postalCode': '4135', 'city': 'AJIM', 'governorate': 'MEDENINE'},
  {'postalCode': '4134', 'city': 'CHAMMAKH', 'governorate': 'MEDENINE'},
  {'postalCode': '4133', 'city': 'ROBBANA', 'governorate': 'MEDENINE'},
  {'postalCode': '4132', 'city': 'HALG JEMAL', 'governorate': 'MEDENINE'},
  {'postalCode': '4131', 'city': 'HASSI AMOR', 'governorate': 'MEDENINE'},
  {
    'postalCode': '4130',
    'city': 'MEDENINE EL JADIDA',
    'governorate': 'MEDENINE'
  },
  {
    'postalCode': '4127',
    'city': 'MEDENINE PERSEVERANCE',
    'governorate': 'MEDENINE'
  },
  {'postalCode': '4126', 'city': 'BENI MAAGUEL', 'governorate': 'MEDENINE'},
  {'postalCode': '4125', 'city': 'EL GROO', 'governorate': 'MEDENINE'},
  {'postalCode': '4124', 'city': 'EL HICHEM', 'governorate': 'MEDENINE'},
  {'postalCode': '4123', 'city': 'OUALEGH', 'governorate': 'MEDENINE'},
  {'postalCode': '4122', 'city': 'KSAR EL JIRA', 'governorate': 'MEDENINE'},
  {'postalCode': '4121', 'city': 'KOUTINE', 'governorate': 'MEDENINE'},
  {'postalCode': '4120', 'city': 'DJERBA AEROPORT', 'governorate': 'MEDENINE'},
  {'postalCode': '4117', 'city': 'JORF', 'governorate': 'MEDENINE'},
  {'postalCode': '4116', 'city': 'MIDOUN', 'governorate': 'MEDENINE'},
  {'postalCode': '4115', 'city': 'DJERBA MELLITA', 'governorate': 'MEDENINE'},
  {'postalCode': '4114', 'city': 'ERRAJA', 'governorate': 'MEDENINE'},
  {'postalCode': '4113', 'city': 'OULED AMOR', 'governorate': 'MEDENINE'},
  {'postalCode': '4112', 'city': 'OUERJIJENE', 'governorate': 'MEDENINE'},
  {'postalCode': '4111', 'city': 'OUM ETTAMAR', 'governorate': 'MEDENINE'},
  {'postalCode': '4110', 'city': 'BENI KHEDACHE', 'governorate': 'MEDENINE'},
  {'postalCode': '4100', 'city': 'MEDENINE', 'governorate': 'MEDENINE'},
  {'postalCode': '4099', 'city': "M'SAKEN EL KEBLIA", 'governorate': 'SOUSSE'},
  {'postalCode': '4095', 'city': 'AIN MEDHEKER', 'governorate': 'SOUSSE'},
  {'postalCode': '4092', 'city': 'AIN ERRAHMA', 'governorate': 'SOUSSE'},
  {'postalCode': '4089', 'city': 'EL KANTAOUI', 'governorate': 'SOUSSE'},
  {'postalCode': '4082', 'city': 'SIDI KHELIFA', 'governorate': 'SOUSSE'},
  {'postalCode': '4081', 'city': 'ZAOUIET SOUSSE', 'governorate': 'SOUSSE'},
  {'postalCode': '4071', 'city': 'KHEZEMA OUEST', 'governorate': 'SOUSSE'},
  {'postalCode': '4070', 'city': 'MSAKEN', 'governorate': 'SOUSSE'},
  {'postalCode': '4063', 'city': 'CHIAB', 'governorate': 'SOUSSE'},
  {
    'postalCode': '4061',
    'city': 'SOUSSE IBN KHALDOUN',
    'governorate': 'SOUSSE'
  },
  {'postalCode': '4060', 'city': 'KALAA KEBIRA', 'governorate': 'SOUSSE'},
  {'postalCode': '4059', 'city': 'SOUSSE COLIS', 'governorate': 'SOUSSE'},
  {'postalCode': '4054', 'city': 'SAHLOUL 3', 'governorate': 'SOUSSE'},
  {'postalCode': '4051', 'city': 'SOUSSE KHEZAMA', 'governorate': 'SOUSSE'},
  {'postalCode': '4045', 'city': 'ESSAD NORD', 'governorate': 'SOUSSE'},
  {'postalCode': '4043', 'city': 'MZEL GARE', 'governorate': 'SOUSSE'},
  {'postalCode': '4042', 'city': 'CHATT MARIEM', 'governorate': 'SOUSSE'},
  {'postalCode': '4041', 'city': 'KSIBET SOUSSE', 'governorate': 'SOUSSE'},
  {'postalCode': '4040', 'city': 'SIDI BOU ALI', 'governorate': 'SOUSSE'},
  {'postalCode': '4035', 'city': 'AIN GARCI', 'governorate': 'SOUSSE'},
  {'postalCode': '4034', 'city': 'CHAGARNIA', 'governorate': 'SOUSSE'},
  {'postalCode': '4033', 'city': 'MOUREDDINE', 'governorate': 'SOUSSE'},
  {'postalCode': '4032', 'city': 'MZEL BEL OUAR', 'governorate': 'SOUSSE'},
  {'postalCode': '4031', 'city': 'SOUSSE EZZOUHOUR', 'governorate': 'SOUSSE'},
  {'postalCode': '4030', 'city': 'ENFIDHA', 'governorate': 'SOUSSE'},
  {'postalCode': '4029', 'city': 'THRAYET', 'governorate': 'SOUSSE'},
  {'postalCode': '4026', 'city': 'KROUSSIA', 'governorate': 'SOUSSE'},
  {'postalCode': '4025', 'city': 'SIDI EL HANI', 'governorate': 'SOUSSE'},
  {'postalCode': '4024', 'city': "M'SAKEN HAY JEDID", 'governorate': 'SOUSSE'},
  {'postalCode': '4023', 'city': 'SOUSSE RIADH', 'governorate': 'SOUSSE'},
  {'postalCode': '4022', 'city': 'AKOUDA', 'governorate': 'SOUSSE'},
  {'postalCode': '4021', 'city': 'KALAA ESSEGHIRA', 'governorate': 'SOUSSE'},
  {'postalCode': '4020', 'city': 'KONDAR', 'governorate': 'SOUSSE'},
  {'postalCode': '4016', 'city': 'BENI KALTHOUM', 'governorate': 'SOUSSE'},
  {'postalCode': '4015', 'city': 'EL BORJINE', 'governorate': 'SOUSSE'},
  {'postalCode': '4014', 'city': 'EL KHENAIES', 'governorate': 'SOUSSE'},
  {'postalCode': '4013', 'city': 'MESSADINE', 'governorate': 'SOUSSE'},
  {'postalCode': '4012', 'city': 'HERGLA', 'governorate': 'SOUSSE'},
  {'postalCode': '4011', 'city': 'HAMMAM SOUSSE', 'governorate': 'SOUSSE'},
  {'postalCode': '4010', 'city': 'BOU FICHA', 'governorate': 'SOUSSE'},
  {
    'postalCode': '4003',
    'city': 'CITE ETTAAMIR SOUSSE',
    'governorate': 'SOUSSE'
  },
  {'postalCode': '4000', 'city': 'SOUSSE', 'governorate': 'SOUSSE'},
  {'postalCode': '3293', 'city': 'ROGBA', 'governorate': 'TATAOUINE'},
  {'postalCode': '3286', 'city': 'NEKRIF', 'governorate': 'TATAOUINE'},
  {'postalCode': '3284', 'city': 'BIR THALTHINE', 'governorate': 'TATAOUINE'},
  {
    'postalCode': '3282',
    'city': 'KSAR OULED SOLTAN',
    'governorate': 'TATAOUINE'
  },
  {
    'postalCode': '3274',
    'city': 'CHENINI NOUVELLE',
    'governorate': 'TATAOUINE'
  },
  {
    'postalCode': '3272',
    'city': 'TATAOUINE EZZAHRA',
    'governorate': 'TATAOUINE'
  },
  {'postalCode': '3271', 'city': 'GUERMASSA', 'governorate': 'TATAOUINE'},
  {'postalCode': '3264', 'city': 'RAS EL OUED', 'governorate': 'TATAOUINE'},
  {
    'postalCode': '3263',
    'city': 'TATAOUINE 7 NOVEMBRE',
    'governorate': 'TATAOUINE'
  },
  {'postalCode': '3262', 'city': 'BENI MEHIRA', 'governorate': 'TATAOUINE'},
  {'postalCode': '3261', 'city': 'KSAR EL HEDADA', 'governorate': 'TATAOUINE'},
  {'postalCode': '3253', 'city': 'DHEHIBET', 'governorate': 'TATAOUINE'},
  {'postalCode': '3252', 'city': 'MAZTOURIA', 'governorate': 'TATAOUINE'},
  {
    'postalCode': '3251',
    'city': 'KSAR EL MOURABETINE',
    'governorate': 'TATAOUINE'
  },
  {'postalCode': '3245', 'city': 'KAMBOUT', 'governorate': 'TATAOUINE'},
  {'postalCode': '3244', 'city': 'BIR AMIR', 'governorate': 'TATAOUINE'},
  {'postalCode': '3243', 'city': 'OUED EL GHAR', 'governorate': 'TATAOUINE'},
  {'postalCode': '3242', 'city': 'KSAR DEBAB', 'governorate': 'TATAOUINE'},
  {'postalCode': '3241', 'city': 'EL FARECH', 'governorate': 'TATAOUINE'},
  {'postalCode': '3240', 'city': 'REMADA', 'governorate': 'TATAOUINE'},
  {'postalCode': '3235', 'city': 'OUED EL KHIL', 'governorate': 'TATAOUINE'},
  {'postalCode': '3233', 'city': 'GATTOUFA', 'governorate': 'TATAOUINE'},
  {'postalCode': '3232', 'city': 'DOUIRET', 'governorate': 'TATAOUINE'},
  {'postalCode': '3225', 'city': 'KIRCHAOU', 'governorate': 'TATAOUINE'},
  {'postalCode': '3224', 'city': 'EL HOURRIA', 'governorate': 'TATAOUINE'},
  {'postalCode': '3223', 'city': 'SMAR', 'governorate': 'TATAOUINE'},
  {'postalCode': '3222', 'city': 'CHENINI', 'governorate': 'TATAOUINE'},
  {'postalCode': '3221', 'city': "KSAR M'GUEBLA", 'governorate': 'TATAOUINE'},
  {'postalCode': '3220', 'city': 'GHOMRASSEN', 'governorate': 'TATAOUINE'},
  {'postalCode': '3215', 'city': 'BENI BARKA', 'governorate': 'TATAOUINE'},
  {'postalCode': '3214', 'city': 'TLELET', 'governorate': 'TATAOUINE'},
  {'postalCode': '3213', 'city': 'KSAR OUN', 'governorate': 'TATAOUINE'},
  {'postalCode': '3212', 'city': 'BIR LAHMAR', 'governorate': 'TATAOUINE'},
  {'postalCode': '3211', 'city': 'TOUNKET', 'governorate': 'TATAOUINE'},
  {'postalCode': '3200', 'city': 'TATAOUINE', 'governorate': 'TATAOUINE'},
  {
    'postalCode': '3199',
    'city': 'CITE IBN EL JAZZAR',
    'governorate': 'KAIROUAN'
  },
  {'postalCode': '3198', 'city': 'EL BORJI', 'governorate': 'KAIROUAN'},
  {'postalCode': '3196', 'city': 'HENDI ZITOUNA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3195', 'city': 'SIDI MESSAOUD', 'governorate': 'KAIROUAN'},
  {'postalCode': '3194', 'city': 'DHRIAAT', 'governorate': 'KAIROUAN'},
  {'postalCode': '3193', 'city': 'EL GHABETE', 'governorate': 'KAIROUAN'},
  {'postalCode': '3192', 'city': 'EL KHADHRA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3191', 'city': 'RACCADA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3183', 'city': 'ABIDA CHARGUIA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3182', 'city': 'CITE ENNASR', 'governorate': 'KAIROUAN'},
  {'postalCode': '3181', 'city': 'BIR EDDAOULA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3180', 'city': 'BOUHAJLA', 'governorate': 'KAIROUAN'},
  {
    'postalCode': '3173',
    'city': 'ERRAGOUBA EL HAMRA',
    'governorate': 'KAIROUAN'
  },
  {'postalCode': '3171', 'city': 'EL KABARA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3170', 'city': 'NASSRALLAH', 'governorate': 'KAIROUAN'},
  {'postalCode': '3161', 'city': 'EL AOUAMRIA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3160', 'city': 'HAJEB EL AYOUN', 'governorate': 'KAIROUAN'},
  {'postalCode': '3154', 'city': 'MESSIOUTA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3153', 'city': 'EL MEDDAID', 'governorate': 'KAIROUAN'},
  {'postalCode': '3152', 'city': 'BIR AHMED', 'governorate': 'KAIROUAN'},
  {'postalCode': '3151', 'city': 'ZAAFRANA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3150', 'city': 'AL ALA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3145', 'city': 'OULED FARJALLAH', 'governorate': 'KAIROUAN'},
  {'postalCode': '3143', 'city': 'AIN EL KHAZAZIA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3142', 'city': 'EL BATTEN', 'governorate': 'KAIROUAN'},
  {'postalCode': '3140', 'city': 'KAIROUAN OKBA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3135', 'city': 'AIN BOUMOURRA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3134', 'city': 'KHIL EL OUED', 'governorate': 'KAIROUAN'},
  {'postalCode': '3133', 'city': 'EL KARMA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3132', 'city': 'SISSEB', 'governorate': 'KAIROUAN'},
  {'postalCode': '3131', 'city': 'KAIROUAN SUD', 'governorate': 'KAIROUAN'},
  {'postalCode': '3130', 'city': 'HAFFOUZ', 'governorate': 'KAIROUAN'},
  {'postalCode': '3129', 'city': 'CITE EL HAJJEM', 'governorate': 'KAIROUAN'},
  {'postalCode': '3126', 'city': 'JHINA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3125', 'city': 'EL ALEM', 'governorate': 'KAIROUAN'},
  {'postalCode': '3124', 'city': 'KSAR LAMSA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3121', 'city': 'CHEBIKA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3120', 'city': 'OUESLATIA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3116', 'city': 'CHERARDA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3115', 'city': 'SIDI SAAD', 'governorate': 'KAIROUAN'},
  {'postalCode': '3114', 'city': 'MENZEL MHIRI', 'governorate': 'KAIROUAN'},
  {'postalCode': '3113', 'city': 'AIN JALLOULA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3112', 'city': 'BEN SALEM', 'governorate': 'KAIROUAN'},
  {'postalCode': '3111', 'city': 'EL MOUTBASTA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3110', 'city': 'SBIKHA', 'governorate': 'KAIROUAN'},
  {'postalCode': '3100', 'city': 'KAIROUAN', 'governorate': 'KAIROUAN'},
  {'postalCode': '3099', 'city': 'EL BOUSTEN', 'governorate': 'SFAX'},
  {'postalCode': '3097', 'city': 'REBAYA SIDI DHAHER', 'governorate': 'SFAX'},
  {'postalCode': '3095', 'city': 'DHRAA BEN ZIAD', 'governorate': 'SFAX'},
  {'postalCode': '3094', 'city': 'CITE BOURGUIBA', 'governorate': 'SFAX'},
  {'postalCode': '3093', 'city': 'MERKEZ OUALI', 'governorate': 'SFAX'},
  {'postalCode': '3092', 'city': 'BOU JARBOU', 'governorate': 'SFAX'},
  {'postalCode': '3091', 'city': 'SIDI SALAH', 'governorate': 'SFAX'},
  {'postalCode': '3089', 'city': 'ENNIGROU', 'governorate': 'SFAX'},
  {'postalCode': '3087', 'city': 'BELIANA', 'governorate': 'SFAX'},
  {'postalCode': '3086', 'city': 'AJENGA', 'governorate': 'SFAX'},
  {'postalCode': '3085', 'city': 'OUM CHOUCHA', 'governorate': 'SFAX'},
  {'postalCode': '3084', 'city': 'TYNA EL JADIDA', 'governorate': 'SFAX'},
  {'postalCode': '3083', 'city': 'TYNA', 'governorate': 'SFAX'},
  {'postalCode': '3082', 'city': 'EL GUENDOUL', 'governorate': 'SFAX'},
  {'postalCode': '3081', 'city': 'ESSALTANIA', 'governorate': 'SFAX'},
  {'postalCode': '3080', 'city': 'JEBENIANA', 'governorate': 'SFAX'},
  {'postalCode': '3079', 'city': 'HAI EL KHIRI', 'governorate': 'SFAX'},
  {'postalCode': '3078', 'city': 'EL HAJEB', 'governorate': 'SFAX'},
  {'postalCode': '3077', 'city': 'DOUAR LIOUATA', 'governorate': 'SFAX'},
  {'postalCode': '3076', 'city': 'MERKEZ  ALOUI', 'governorate': 'SFAX'},
  {'postalCode': '3075', 'city': 'MERKEZ SGHAR', 'governorate': 'SFAX'},
  {'postalCode': '3074', 'city': 'EL AOUABED', 'governorate': 'SFAX'},
  {'postalCode': '3073', 'city': 'SBIH', 'governorate': 'SFAX'},
  {'postalCode': '3072', 'city': 'MERKEZ CHAKER', 'governorate': 'SFAX'},
  {'postalCode': '3071', 'city': 'OUED CHAABOUNI', 'governorate': 'SFAX'},
  {'postalCode': '3070', 'city': 'KHERKENAH', 'governorate': 'SFAX'},
  {'postalCode': '3069', 'city': 'SFAX HACHED', 'governorate': 'SFAX'},
  {'postalCode': '3067', 'city': 'SAKIET EDDAIER SFAX', 'governorate': 'SFAX'},
  {'postalCode': '3066', 'city': 'ESSAADI', 'governorate': 'SFAX'},
  {'postalCode': '3065', 'city': 'SFAX PORT', 'governorate': 'SFAX'},
  {'postalCode': '3064', 'city': 'CITE EL BAHRI', 'governorate': 'SFAX'},
  {'postalCode': '3063', 'city': 'EL KHALIJ', 'governorate': 'SFAX'},
  {'postalCode': '3062', 'city': 'SIDI ABBES', 'governorate': 'SFAX'},
  {'postalCode': '3061', 'city': 'SIDI MANSOUR', 'governorate': 'SFAX'},
  {'postalCode': '3060', 'city': 'MAHRES', 'governorate': 'SFAX'},
  {'postalCode': '3059', 'city': 'EL KHAZZANETTE', 'governorate': 'SFAX'},
  {'postalCode': '3057', 'city': 'JEBERNA', 'governorate': 'SFAX'},
  {'postalCode': '3056', 'city': 'OULED BOUSMIR', 'governorate': 'SFAX'},
  {'postalCode': '3055', 'city': 'EL KRATEN', 'governorate': 'SFAX'},
  {'postalCode': '3054', 'city': 'MERKEZ SEBAI', 'governorate': 'SFAX'},
  {'postalCode': '3053', 'city': 'SIDI HASSEN', 'governorate': 'SFAX'},
  {'postalCode': '3052', 'city': 'CITE EL HABIB', 'governorate': 'SFAX'},
  {'postalCode': '3051', 'city': 'MERKEZ EL ALIA', 'governorate': 'SFAX'},
  {'postalCode': '3050', 'city': 'SKHIRA', 'governorate': 'SFAX'},
  {'postalCode': '3049', 'city': 'SFAX MAGHREB ARABE', 'governorate': 'SFAX'},
  {'postalCode': '3046', 'city': 'ESSALEM', 'governorate': 'SFAX'},
  {'postalCode': '3045', 'city': 'ENNAJET', 'governorate': 'SFAX'},
  {'postalCode': '3044', 'city': 'NEKTA', 'governorate': 'SFAX'},
  {'postalCode': '3043', 'city': 'EL GHRABA', 'governorate': 'SFAX'},
  {'postalCode': '3042', 'city': 'EL AIN', 'governorate': 'SFAX'},
  {'postalCode': '3041', 'city': 'MERKEZ CHIHYA', 'governorate': 'SFAX'},
  {'postalCode': '3040', 'city': 'BIR ALI BEN KHELIFA', 'governorate': 'SFAX'},
  {'postalCode': '3039', 'city': "CAID M'HAMED", 'governorate': 'SFAX'},
  {'postalCode': '3037', 'city': 'GARGOUR', 'governorate': 'SFAX'},
  {'postalCode': '3036', 'city': 'EL AMRA', 'governorate': 'SFAX'},
  {'postalCode': '3035', 'city': 'EL ATTAYA', 'governorate': 'SFAX'},
  {'postalCode': '3034', 'city': 'GHRAIBA', 'governorate': 'SFAX'},
  {'postalCode': '3033', 'city': 'BIR SALAH', 'governorate': 'SFAX'},
  {'postalCode': '3032', 'city': 'MERKEZ DEROUICHE', 'governorate': 'SFAX'},
  {'postalCode': '3031', 'city': 'MERKEZ BOUACIDA', 'governorate': 'SFAX'},
  {'postalCode': '3030', 'city': 'AGAREB', 'governorate': 'SFAX'},
  {'postalCode': '3027', 'city': 'SFAX EL JADIDA', 'governorate': 'SFAX'},
  {'postalCode': '3026', 'city': 'HAZEG', 'governorate': 'SFAX'},
  {'postalCode': '3025', 'city': 'OUED KACEM', 'governorate': 'SFAX'},
  {'postalCode': '3024', 'city': 'CHAAL', 'governorate': 'SFAX'},
  {'postalCode': '3023', 'city': 'OUED RMAL', 'governorate': 'SFAX'},
  {'postalCode': '3022', 'city': 'MERKEZ KAMMOUN', 'governorate': 'SFAX'},
  {'postalCode': '3021', 'city': 'SAKIET EZZIT', 'governorate': 'SFAX'},
  {'postalCode': '3020', 'city': 'MZEL HEDI CHAKER', 'governorate': 'SFAX'},
  {'postalCode': '3018', 'city': 'SFAX.', 'governorate': 'SFAX'},
  {'postalCode': '3016', 'city': 'EL LOUZA', 'governorate': 'SFAX'},
  {'postalCode': '3015', 'city': 'MELLIATA', 'governorate': 'SFAX'},
  {'postalCode': '3014', 'city': 'BOU THADDI', 'governorate': 'SFAX'},
  {'postalCode': '3013', 'city': 'MERKEZ KASSAS', 'governorate': 'SFAX'},
  {'postalCode': '3012', 'city': 'MERKEZ SAHNOUN', 'governorate': 'SFAX'},
  {'postalCode': '3011', 'city': 'SAKIET EDDAIER', 'governorate': 'SFAX'},
  {'postalCode': '3010', 'city': 'EL HENCHA', 'governorate': 'SFAX'},
  {'postalCode': '3000', 'city': 'SFAX', 'governorate': 'SFAX'},
  {'postalCode': '2263', 'city': 'BOU HLEL', 'governorate': 'TOZEUR'},
  {'postalCode': '2262', 'city': 'DGHOUMES', 'governorate': 'TOZEUR'},
  {'postalCode': '2261', 'city': 'SABAA ABAR', 'governorate': 'TOZEUR'},
  {'postalCode': '2260', 'city': 'DEGUECHE', 'governorate': 'TOZEUR'},
  {'postalCode': '2253', 'city': 'CHEBIKA DU JERID', 'governorate': 'TOZEUR'},
  {'postalCode': '2245', 'city': 'BEN FARJALLAH', 'governorate': 'TOZEUR'},
  {'postalCode': '2243', 'city': 'TOZEUR AEROPORT', 'governorate': 'TOZEUR'},
  {'postalCode': '2241', 'city': 'RAS DHRAA', 'governorate': 'TOZEUR'},
  {'postalCode': '2240', 'city': 'NEFTA', 'governorate': 'TOZEUR'},
  {'postalCode': '2239', 'city': 'CHETAOUA SAHRAOUI', 'governorate': 'TOZEUR'},
  {'postalCode': '2233', 'city': 'BLED EL HADHAR', 'governorate': 'TOZEUR'},
  {'postalCode': '2224', 'city': 'EL MAHASSEN', 'governorate': 'TOZEUR'},
  {'postalCode': '2223', 'city': 'HEZOUA', 'governorate': 'TOZEUR'},
  {'postalCode': '2214', 'city': 'HAMMET EL JERID', 'governorate': 'TOZEUR'},
  {'postalCode': '2212', 'city': 'TAMEGHZA', 'governorate': 'TOZEUR'},
  {'postalCode': '2211', 'city': 'DHAFRIA', 'governorate': 'TOZEUR'},
  {'postalCode': '2210', 'city': 'TOZEUR CHOKRATSI', 'governorate': 'TOZEUR'},
  {'postalCode': '2200', 'city': 'TOZEUR', 'governorate': 'TOZEUR'},
  {'postalCode': '2196', 'city': 'ECHABIBA', 'governorate': 'GAFSA'},
  {'postalCode': '2195', 'city': 'ALIM', 'governorate': 'GAFSA'},
  {'postalCode': '2193', 'city': 'ABDESSADOK', 'governorate': 'GAFSA'},
  {'postalCode': '2192', 'city': 'MAJOURA', 'governorate': 'GAFSA'},
  {'postalCode': '2190', 'city': 'SNED', 'governorate': 'GAFSA'},
  {'postalCode': '2183', 'city': 'LORTES', 'governorate': 'GAFSA'},
  {'postalCode': '2181', 'city': 'NICHIOU', 'governorate': 'GAFSA'},
  {'postalCode': '2180', 'city': 'EL GUETTAR', 'governorate': 'GAFSA'},
  {'postalCode': '2173', 'city': 'BORJ EL MDHILA', 'governorate': 'GAFSA'},
  {'postalCode': '2170', 'city': 'JEBEL MEDHILA', 'governorate': 'GAFSA'},
  {'postalCode': '2169', 'city': 'ERRAGOUBA', 'governorate': 'GAFSA'},
  {'postalCode': '2161', 'city': 'MOULARES GARE', 'governorate': 'GAFSA'},
  {'postalCode': '2151', 'city': 'GAFSA AEROPORT', 'governorate': 'GAFSA'},
  {'postalCode': '2143', 'city': 'DOUALY GAFSA', 'governorate': 'GAFSA'},
  {'postalCode': '2142', 'city': 'KEF DERBI', 'governorate': 'GAFSA'},
  {'postalCode': '2141', 'city': 'MZEL MIMOUN', 'governorate': 'GAFSA'},
  {'postalCode': '2140', 'city': 'REDEYEF GARE', 'governorate': 'GAFSA'},
  {'postalCode': '2139', 'city': 'EL AYAICHA', 'governorate': 'GAFSA'},
  {'postalCode': '2135', 'city': 'HAOUEL EL OUED', 'governorate': 'GAFSA'},
  {'postalCode': '2134', 'city': 'METLAOUI THALJA', 'governorate': 'GAFSA'},
  {
    'postalCode': '2133',
    'city': 'GAFSA CITE DES JEUNES',
    'governorate': 'GAFSA'
  },
  {'postalCode': '2132', 'city': 'METLAOUI MINE', 'governorate': 'GAFSA'},
  {'postalCode': '2131', 'city': 'SIDI AICH', 'governorate': 'GAFSA'},
  {'postalCode': '2130', 'city': 'METLAOUI', 'governorate': 'GAFSA'},
  {'postalCode': '2125', 'city': 'BOU OMRANE', 'governorate': 'GAFSA'},
  {'postalCode': '2122', 'city': 'ZOMARA REDEYEF', 'governorate': 'GAFSA'},
  {'postalCode': '2121', 'city': 'LALA', 'governorate': 'GAFSA'},
  {'postalCode': '2120', 'city': 'REDEYEF', 'governorate': 'GAFSA'},
  {'postalCode': '2116', 'city': 'ZANNOUCHE', 'governorate': 'GAFSA'},
  {'postalCode': '2115', 'city': 'BEL KHIR', 'governorate': 'GAFSA'},
  {'postalCode': '2114', 'city': 'SIDI BOUBAKER', 'governorate': 'GAFSA'},
  {'postalCode': '2113', 'city': 'METLAOUI GARE', 'governorate': 'GAFSA'},
  {'postalCode': '2112', 'city': 'SIDI AHMED ZARROUK', 'governorate': 'GAFSA'},
  {'postalCode': '2111', 'city': 'GAFSA GARE', 'governorate': 'GAFSA'},
  {'postalCode': '2110', 'city': 'MOULARES', 'governorate': 'GAFSA'},
  {'postalCode': '2100', 'city': 'GAFSA', 'governorate': 'GAFSA'},
  {'postalCode': '2099', 'city': 'CITE BOUSSOFARA', 'governorate': 'BEN AROUS'},
  {'postalCode': '2098', 'city': 'RADES MEDINA', 'governorate': 'BEN AROUS'},
  {'postalCode': '2097', 'city': 'BOU MHEL', 'governorate': 'BEN AROUS'},
  {'postalCode': '2096', 'city': 'EL YASMINETTE', 'governorate': 'BEN AROUS'},
  {'postalCode': '2095', 'city': 'ETTADHAMEN II', 'governorate': 'ARIANA'},
  {'postalCode': '2094', 'city': "M'NIHLA", 'governorate': 'ARIANA'},
  {'postalCode': '2093', 'city': 'BOUKORNINE', 'governorate': 'BEN AROUS'},
  {'postalCode': '2092', 'city': 'ELMANAR 2', 'governorate': 'TUNIS'},
  {'postalCode': '2091', 'city': 'EL MENZAH VI', 'governorate': 'ARIANA'},
  {'postalCode': '2090', 'city': 'MORNAG', 'governorate': 'BEN AROUS'},
  {'postalCode': '2089', 'city': 'LE KRAM OUEST', 'governorate': 'TUNIS'},
  {
    'postalCode': '2088',
    'city': 'POLE TECHNOLOGIQUE EL GHAZALA',
    'governorate': 'ARIANA'
  },
  {'postalCode': '2087', 'city': 'ELHRAIRIA', 'governorate': 'TUNIS'},
  {
    'postalCode': '2086',
    'city': 'DOUAR HICHER MANOUBA',
    'governorate': 'MANNOUBA'
  },
  {'postalCode': '2085', 'city': 'CARTHAGE YASMINA', 'governorate': 'TUNIS'},
  {'postalCode': '2084', 'city': 'BORJ CEDRIA', 'governorate': 'BEN AROUS'},
  {'postalCode': '2083', 'city': 'CITE EL GHAZALA', 'governorate': 'ARIANA'},
  {'postalCode': '2082', 'city': 'FOUCHANA', 'governorate': 'BEN AROUS'},
  {'postalCode': '2081', 'city': 'BORJ TOUIL', 'governorate': 'ARIANA'},
  {'postalCode': '2080', 'city': 'ARIANA', 'governorate': 'ARIANA'},
  {'postalCode': '2079', 'city': 'TUNIS AEROPORT', 'governorate': 'TUNIS'},
  {'postalCode': '2078', 'city': 'MARSA SAFSAF', 'governorate': 'TUNIS'},
  {'postalCode': '2076', 'city': 'MARSA  ERRIADH', 'governorate': 'TUNIS'},
  {'postalCode': '2075', 'city': 'EL MANSOURA', 'governorate': 'MANNOUBA'},
  {'postalCode': '2074', 'city': 'ELMOUROUJ', 'governorate': 'BEN AROUS'},
  {'postalCode': '2073', 'city': 'BORJ LOUZIR', 'governorate': 'ARIANA'},
  {'postalCode': '2072', 'city': 'CITE HELLAL', 'governorate': 'TUNIS'},
  {
    'postalCode': '2071',
    'city': 'SIDI ALI EL HATTAB',
    'governorate': 'MANNOUBA'
  },
  {'postalCode': '2070', 'city': 'MARSA', 'governorate': 'TUNIS'},
  {'postalCode': '2066', 'city': 'IBN SINA', 'governorate': 'TUNIS'},
  {
    'postalCode': '2065',
    'city': 'EZZAHRA EL HABIB',
    'governorate': 'BEN AROUS'
  },
  {'postalCode': '2064', 'city': 'LA LAVERIE', 'governorate': 'BEN AROUS'},
  {'postalCode': '2063', 'city': 'NOUVELLE MEDINA', 'governorate': 'BEN AROUS'},
  {'postalCode': '2062', 'city': 'CITE IBN KHALDOUN', 'governorate': 'TUNIS'},
  {'postalCode': '2061', 'city': 'PONT DE BIZERTE', 'governorate': 'ARIANA'},
  {'postalCode': '2060', 'city': 'LA GOULETTE', 'governorate': 'TUNIS'},
  {'postalCode': '2059', 'city': 'BIR EL KASSAA', 'governorate': 'BEN AROUS'},
  {'postalCode': '2058', 'city': 'RIADH LANDLOUS', 'governorate': 'ARIANA'},
  {'postalCode': '2057', 'city': 'CHORFECH', 'governorate': 'ARIANA'},
  {'postalCode': '2056', 'city': 'RAOUED', 'governorate': 'ARIANA'},
  {'postalCode': '2055', 'city': 'BIR EL BEY', 'governorate': 'BEN AROUS'},
  {'postalCode': '2054', 'city': 'KHELIDIA', 'governorate': 'BEN AROUS'},
  {'postalCode': '2053', 'city': 'KABARIA', 'governorate': 'TUNIS'},
  {'postalCode': '2052', 'city': 'CITE EZZOUHOUR', 'governorate': 'TUNIS'},
  {'postalCode': '2051', 'city': 'EZZAHROUNI', 'governorate': 'TUNIS'},
  {'postalCode': '2050', 'city': 'HAMMAM LIF', 'governorate': 'BEN AROUS'},
  {'postalCode': '2046', 'city': 'SIDI DAOUD', 'governorate': 'TUNIS'},
  {'postalCode': '2045', 'city': 'CITE MHIRI', 'governorate': 'TUNIS'},
  {'postalCode': '2044', 'city': 'ERRISSALA', 'governorate': 'BEN AROUS'},
  {'postalCode': '2043', 'city': 'BEN AROUS SUD', 'governorate': 'BEN AROUS'},
  {'postalCode': '2042', 'city': 'CITE ETTAHRIR', 'governorate': 'TUNIS'},
  {'postalCode': '2041', 'city': 'ETTADHAMEN', 'governorate': 'ARIANA'},
  {'postalCode': '2040', 'city': 'RADES', 'governorate': 'BEN AROUS'},
  {'postalCode': '2037', 'city': 'EL NASR', 'governorate': 'ARIANA'},
  {'postalCode': '2036', 'city': 'LA SOUKRA', 'governorate': 'ARIANA'},
  {'postalCode': '2035', 'city': 'TUNIS CARTHAGE', 'governorate': 'ARIANA'},
  {'postalCode': '2034', 'city': 'EZZAHRA', 'governorate': 'BEN AROUS'},
  {'postalCode': '2033', 'city': 'MEGRINE', 'governorate': 'BEN AROUS'},
  {'postalCode': '2032', 'city': 'CEBALET BEN AMMAR', 'governorate': 'ARIANA'},
  {'postalCode': '2031', 'city': 'ESSAIDA', 'governorate': 'MANNOUBA'},
  {'postalCode': '2030', 'city': 'SIJOUMI', 'governorate': 'TUNIS'},
  {'postalCode': '2028', 'city': 'EL BASSATINE', 'governorate': 'MANNOUBA'},
  {'postalCode': '2026', 'city': 'SIDI BOU SAID', 'governorate': 'TUNIS'},
  {'postalCode': '2025', 'city': 'SALAMMBO', 'governorate': 'TUNIS'},
  {'postalCode': '2024', 'city': 'MEGRINE CHAKER', 'governorate': 'BEN AROUS'},
  {'postalCode': '2023', 'city': 'SIDI FATHALLAH', 'governorate': 'TUNIS'},
  {'postalCode': '2022', 'city': 'KALAAT EL ANDALOUS', 'governorate': 'ARIANA'},
  {'postalCode': '2021', 'city': 'OUED ELLIL', 'governorate': 'MANNOUBA'},
  {'postalCode': '2020', 'city': 'SIDI THABET', 'governorate': 'ARIANA'},
  {'postalCode': '2017', 'city': 'KHAZNADAR', 'governorate': 'TUNIS'},
  {'postalCode': '2016', 'city': 'CARTHAGE', 'governorate': 'TUNIS'},
  {'postalCode': '2015', 'city': 'LE KRAM', 'governorate': 'TUNIS'},
  {'postalCode': '2014', 'city': 'MEGRINE RIADH', 'governorate': 'BEN AROUS'},
  {'postalCode': '2013', 'city': 'BEN AROUS', 'governorate': 'BEN AROUS'},
  {'postalCode': '2012', 'city': 'EL HABIBIA', 'governorate': 'MANNOUBA'},
  {'postalCode': '2011', 'city': 'DEN DEN', 'governorate': 'MANNOUBA'},
  {'postalCode': '2010', 'city': 'LA MANOUBA', 'governorate': 'MANNOUBA'},
  {'postalCode': '2009', 'city': 'KSAR SAID', 'governorate': 'TUNIS'},
  {'postalCode': '2001', 'city': 'RIADH ENNASR II', 'governorate': 'TUNIS'},
  {'postalCode': '2000', 'city': 'LE BARDO', 'governorate': 'TUNIS'},
  {'postalCode': '1294', 'city': 'EL FEKKA', 'governorate': 'KASSERINE'},
  {
    'postalCode': '1293',
    'city': 'GARAAT ENNADHOUR',
    'governorate': 'KASSERINE'
  },
  {'postalCode': '1285', 'city': 'AIN EDDEFLA', 'governorate': 'KASSERINE'},
  {'postalCode': '1283', 'city': 'EL MZIRA', 'governorate': 'KASSERINE'},
  {'postalCode': '1281', 'city': 'AIN EL HMADNA', 'governorate': 'KASSERINE'},
  {'postalCode': '1280', 'city': 'JEDLIANE', 'governorate': 'KASSERINE'},
  {
    'postalCode': '1279',
    'city': 'KASSERINE EZZOUHOUR',
    'governorate': 'KASSERINE'
  },
  {
    'postalCode': '1273',
    'city': 'SIDI BRAHIM EZZAHER',
    'governorate': 'KASSERINE'
  },
  {'postalCode': '1271', 'city': 'AIN KHAMAISSIA', 'governorate': 'KASSERINE'},
  {'postalCode': '1270', 'city': 'SBIBA', 'governorate': 'KASSERINE'},
  {'postalCode': '1263', 'city': 'CITE ESSOUROUR', 'governorate': 'KASSERINE'},
  {'postalCode': '1257', 'city': 'DOUAR HICHER', 'governorate': 'LA MANOUBA'},
  {
    'postalCode': '1256',
    'city': 'HENCHIR EL ASSAL',
    'governorate': 'KASSERINE'
  },
  {'postalCode': '1255', 'city': 'OUED MIOU', 'governorate': 'KASSERINE'},
  {
    'postalCode': '1254',
    'city': 'ZAOUIET BEN AMMAR',
    'governorate': 'KASSERINE'
  },
  {'postalCode': '1253', 'city': 'BOU LAABA', 'governorate': 'KASSERINE'},
  {'postalCode': '1252', 'city': 'ERRAHYET', 'governorate': 'KASSERINE'},
  {'postalCode': '1251', 'city': 'ECHRAYA', 'governorate': 'KASSERINE'},
  {'postalCode': '1250', 'city': 'SBEITLA', 'governorate': 'KASSERINE'},
  {
    'postalCode': '1247',
    'city': 'KHANGUET EL JAZIA',
    'governorate': 'KASSERINE'
  },
  {'postalCode': '1245', 'city': 'EL KAMOUR', 'governorate': 'KASSERINE'},
  {'postalCode': '1243', 'city': 'GARRAT ENNAAM', 'governorate': 'KASSERINE'},
  {'postalCode': '1242', 'city': 'LAHOUACHE', 'governorate': 'KASSERINE'},
  {'postalCode': '1241', 'city': 'HASSI EL FERID', 'governorate': 'KASSERINE'},
  {'postalCode': '1240', 'city': 'FERIANA', 'governorate': 'KASSERINE'},
  {'postalCode': '1235', 'city': 'ZELFANE', 'governorate': 'KASSERINE'},
  {'postalCode': '1234', 'city': 'EL GRINE', 'governorate': 'KASSERINE'},
  {'postalCode': '1233', 'city': 'BOUZGHEM', 'governorate': 'KASSERINE'},
  {'postalCode': '1232', 'city': 'BOUDEYRES', 'governorate': 'KASSERINE'},
  {'postalCode': '1231', 'city': 'SIDI SHIL', 'governorate': 'KASSERINE'},
  {'postalCode': '1230', 'city': 'KASSERINE NOUR', 'governorate': 'KASSERINE'},
  {'postalCode': '1226', 'city': 'BARROUKA', 'governorate': 'KASSERINE'},
  {'postalCode': '1225', 'city': 'EL AJRED', 'governorate': 'KASSERINE'},
  {'postalCode': '1224', 'city': 'EDDACHRA', 'governorate': 'KASSERINE'},
  {'postalCode': '1223', 'city': 'CEKHIRATE', 'governorate': 'KASSERINE'},
  {'postalCode': '1222', 'city': 'SAHRAOUI', 'governorate': 'KASSERINE'},
  {'postalCode': '1221', 'city': 'HAIDRA', 'governorate': 'KASSERINE'},
  {'postalCode': '1220', 'city': 'FOUSSANA', 'governorate': 'KASSERINE'},
  {'postalCode': '1216', 'city': 'EL AOUN', 'governorate': 'KASSERINE'},
  {'postalCode': '1215', 'city': 'THELEPE', 'governorate': 'KASSERINE'},
  {'postalCode': '1214', 'city': 'MAJEN BEL ABBES', 'governorate': 'KASSERINE'},
  {'postalCode': '1213', 'city': 'BOU CHEBKHA', 'governorate': 'KASSERINE'},
  {'postalCode': '1212', 'city': 'KHMOUDA', 'governorate': 'KASSERINE'},
  {'postalCode': '1211', 'city': 'BOU LAHNECHE', 'governorate': 'KASSERINE'},
  {'postalCode': '1210', 'city': 'THALA', 'governorate': 'KASSERINE'},
  {'postalCode': '1200', 'city': 'KASSERINE', 'governorate': 'KASSERINE'},
  {'postalCode': '1194', 'city': 'DHRAA BEN JOUDER', 'governorate': 'ZAGHOUAN'},
  {
    'postalCode': '1193',
    'city': "BIR M'CHARGA GARE",
    'governorate': 'ZAGHOUAN'
  },
  {'postalCode': '1164', 'city': 'HAMMAM CHATT', 'governorate': 'BEN AROUS'},
  {'postalCode': '1163', 'city': 'BIR CHAOUCH', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1162', 'city': 'BENT SAIDANE', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1160', 'city': 'ENNADHOUR', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1155', 'city': 'BIR HALIMA', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1154', 'city': 'AIN BATTOUM', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1153', 'city': 'EL FEJJA', 'governorate': 'MANNOUBA'},
  {'postalCode': '1152', 'city': 'HAMMAM ZRIBA', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1146', 'city': 'SIDI AOUIDETTE', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1145', 'city': 'MOHAMEDIA', 'governorate': 'BEN AROUS'},
  {'postalCode': '1144', 'city': 'EDDKHILA', 'governorate': 'MANNOUBA'},
  {'postalCode': '1143', 'city': 'BORJ ETTOUMI', 'governorate': 'MANNOUBA'},
  {'postalCode': '1142', 'city': 'BORJ EL AMRI', 'governorate': 'MANNOUBA'},
  {'postalCode': '1141', 'city': "BIR M'CHARGA", 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1140', 'city': 'EL FAHS', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1135', 'city': 'NAASSEN', 'governorate': 'BEN AROUS'},
  {'postalCode': '1134', 'city': 'CHAOUAT', 'governorate': 'MANNOUBA'},
  {'postalCode': '1133', 'city': 'CHOUIGUIES', 'governorate': 'MANNOUBA'},
  {'postalCode': '1132', 'city': 'OUED EZZIT', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1131', 'city': 'SMINJA', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1130', 'city': 'TEBOURBA', 'governorate': 'MANNOUBA'},
  {'postalCode': '1125', 'city': 'RADES SALINES', 'governorate': 'BEN AROUS'},
  {'postalCode': '1124', 'city': 'JEDAIDA', 'governorate': 'MANNOUBA'},
  {'postalCode': '1123', 'city': 'AIN EL ASKER', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1122', 'city': 'ZRIBA', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1121', 'city': 'EL MAGRAN', 'governorate': 'ZAGHOUAN'},
  {
    'postalCode': '1116',
    'city': 'MORNAGUIA 20 MARS',
    'governorate': 'MANNOUBA'
  },
  {'postalCode': '1115', 'city': 'SAOUEF', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1114', 'city': 'EL BATTAN', 'governorate': 'MANNOUBA'},
  {'postalCode': '1113', 'city': 'EL MOUSSAIDINE', 'governorate': 'MANNOUBA'},
  {'postalCode': '1112', 'city': 'JERADOU', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1111', 'city': 'JEBEL OUST', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1110', 'city': 'EL MORNAGUIA', 'governorate': 'MANNOUBA'},
  {'postalCode': '1100', 'city': 'ZAGHOUAN', 'governorate': 'ZAGHOUAN'},
  {'postalCode': '1095', 'city': 'SIDI  HASSINE', 'governorate': 'TUNIS'},
  {'postalCode': '1091', 'city': 'EL OMRANE SUPERIEUR', 'governorate': 'TUNIS'},
  {'postalCode': '1089', 'city': 'TUNIS CHEBBI', 'governorate': 'TUNIS'},
  {'postalCode': '1082', 'city': 'CITE EL MAHRAGENE', 'governorate': 'TUNIS'},
  {'postalCode': '1080', 'city': 'TUNIS CEDEX', 'governorate': 'TUNIS'},
  {'postalCode': '1079', 'city': 'TUNIS HALLES', 'governorate': 'TUNIS'},
  {
    'postalCode': '1075',
    'city': 'TUNIS BAB  EL  KHADRA',
    'governorate': 'TUNIS'
  },
  {'postalCode': '1074', 'city': 'EL MOUROUJ', 'governorate': 'TUNIS'},
  {'postalCode': '1073', 'city': 'MONTPLAISIR', 'governorate': 'TUNIS'},
  {'postalCode': '1069', 'city': 'TUNIS THAMEUR', 'governorate': 'TUNIS'},
  {'postalCode': '1059', 'city': 'TUNIS EL HAFSIA', 'governorate': 'TUNIS'},
  {'postalCode': '1053', 'city': 'LES BERGES DU LAC', 'governorate': 'TUNIS'},
  {'postalCode': '1049', 'city': 'TUNIS HACHAD', 'governorate': 'TUNIS'},
  {'postalCode': '1029', 'city': 'BAB SAADOUN', 'governorate': 'TUNIS'},
  {'postalCode': '1019', 'city': 'TUNIS BAB BNET', 'governorate': 'TUNIS'},
  {'postalCode': '1013', 'city': 'EL MENZEH 9', 'governorate': 'TUNIS'},
  {'postalCode': '1009', 'city': 'EL OUARDIA', 'governorate': 'TUNIS'},
  {'postalCode': '1008', 'city': 'TUNIS BAB MENARA', 'governorate': 'TUNIS'},
  {'postalCode': '1007', 'city': 'TUNIS JEBBARI', 'governorate': 'TUNIS'},
  {'postalCode': '1006', 'city': 'TUNIS BAB SOUIKA', 'governorate': 'TUNIS'},
  {'postalCode': '1005', 'city': 'EL OMRANE', 'governorate': 'TUNIS'},
  {'postalCode': '1004', 'city': 'EL MENZEH', 'governorate': 'TUNIS'},
  {'postalCode': '1003', 'city': 'CITE EL KHADRA', 'governorate': 'TUNIS'},
  {'postalCode': '1002', 'city': 'TUNIS BELVEDERE', 'governorate': 'TUNIS'},
  {'postalCode': '1001', 'city': 'TUNIS REPUBLIQUE', 'governorate': 'TUNIS'},
  {'postalCode': '1000', 'city': 'TUNIS RP', 'governorate': 'TUNIS'}
];

String getCityByPostalCode(String postalCode) {
  final Iterable<Map<String, String>> city = postalCodesList.where(
    (Map<String, String> element) => element['postalCode'] == postalCode,
  );
  return city.isNotEmpty ? city.first['city'] : null;
}

String getGovernorateByPostalCode(String postalCode) {
  final Iterable<Map<String, String>> city = postalCodesList.where(
    (Map<String, String> element) => element['postalCode'] == postalCode,
  );
  return city.isNotEmpty ? city.first['governorate'] : null;
}
