name: e_loan_mobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # GetX is an extra-light and powerful solution for Flutter. It combines high-performance state management, intelligent dependency injection, and route management quickly and practically.
  get: ^4.1.4

  # Powerful Http client for Dart
  dio: ^4.0.0

  # Helps display an easy, beautiful and customizable loader
  flutter_easyloading: ^3.0.0

  # Back Button Interceptor. May be used to do stuff when the Android back-button is tapped, as an alternative to `WillPopScope`.
  back_button_interceptor: ^5.0.0

  # Flutter plugin for discovering the state of the soft-keyboard visibility on Android and iOS.
  flutter_keyboard_visibility: ^5.0.1

  # Masked text input for flutter.
  flutter_masked_text2: ^0.9.1

  # Common util classes providing a solution for different situations.
  basic_utils: ^3.0.2

  # A flutter package which will help you to generate pin code fields. Can be useful for OTP for example.
  pin_code_fields: ^7.0.0

  # A package that allows you to use a native file explorer to pick single or multiple absolute file paths, with extension filtering support.
  file_picker: ^3.0.1

  # A multi select form field using alert dialog to select multiple items with checkboxes and showing as chips.
  multiselect_formfield: ^0.1.6

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.17.0

  # A plug-in that can call native APP to open files with string result in flutter
  open_file: ^3.2.1

  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes.
  url_launcher: ^6.0.5

  # A simple and customizable flutter package for inputting phone number in intl / international format uses Google's libphonenumber.
  intl_phone_number_input: ^0.7.0+2

  # A carousel slider widget, support infinite scroll and custom child widget.
  carousel_slider: ^3.0.0

  # A highly customizable typeahead (autocomplete) text input field for Flutter
  flutter_typeahead: ^3.1.3

  # Creating selectable and input tags (TextField) has never been easier.
  flutter_tags: ^0.4.9+1

  # Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^2.0.2

  # Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
  permission_handler: ^8.1.2

  # Flutter plugin for Firebase Cloud Messaging, a cross-platform messaging solution that lets you reliably deliver messages on Android and iOS.
  firebase_messaging: ^10.0.4

  #A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform.
  flutter_local_notifications: ^6.0.0

  # Collections and utilities functions and classes related to collections.
  collection: ^1.15.0

  # Flutter plugin providing detailed information about the device (make, model, etc.), and Android or iOS version the app is running on.
  device_info: ^2.0.2

  # Lazily load and display pages of items as the user scrolls down your screen.
  infinite_scroll_pagination: ^3.1.0

  # Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
  connectivity: ^3.0.6

  # Flutter plugin for storing data in device disk on android and ios based on GETX
  get_storage: ^2.0.3

dev_dependencies:
  # A Flutter plugin providing a feature-rich PDF viewing and editing experience to your users with the powerful PSPDFKit PDF SDK
  lint: ^1.5.3

  # A package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.9.0

  # Generates native code to customize Flutter's default white native splash screen with background color and splash image
  flutter_native_splash: ^1.1.8+4

  appcenter: ^0.2.1
  appcenter_analytics: ^0.2.1
  appcenter_crashes: ^0.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700

# flutter pub run flutter_launcher_icons:main OR remove
flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#F5F4F9"

#flutter pub run flutter_native_splash:create OR remove
flutter_native_splash:
  image: assets/images/splash.png
  color: "E4EEF5"
  android: true
  ios: true
  fill: true
